<?php
/**
 * Plugin Name:       GravityView Mod: Remove Edit Entry Nonce Validation
 * Plugin URI:        https://github.com/gravityview/gv-snippets/tree/addon/remove-nonce-validation
 * Description:       Removes Edit Entry "nonce" validation. Edit Entry checks whether an user has the ability to edit an entry, but it also checks a "nonce" to make sure that the Edit Entry link was recently generated by the current user visiting the page. This can sometimes cause problems; this plugin removes that "nonce" validation.
 * Version:           1.0
 * Author:            GravityView
 * Author URI:        https://gravityview.co
 * License:           GPL-2.0+
 * License URI:       http://www.gnu.org/licenses/gpl-2.0.txt
 */

// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ){
	die;
}

add_filter( 'gravityview/edit_entry/verify_nonce', '__return_true' );